// 1. Прямые соответствия: сегмент URL -> ваша категория
export const DIRECT_MAP = {
  //ЭЛЕКТРОНИКА
  'smartfon': 'electronics',
  'telefon': 'electronics',
  'mobile': 'electronics',
  'noutbuk': 'electronics',
  'laptop': 'electronics',
  'kompyutery': 'electronics',
  'kompyuter': 'electronics',
  'planhet': 'electronics',
  'tablet': 'electronics',
  'naushniki': 'electronics',
  'kolonki': 'electronics',
  'monitor': 'electronics',
  'klaviatura': 'electronics',
  'myshka': 'electronics',
  'televizor': 'electronics',
  'tv': 'electronics',
  'smart_chasy': 'electronics',
  'igrovaya_konsol': 'electronics',
  'fotoapparat': 'electronics',
  'kamera': 'electronics',

  //ОДЕЖДА
  'odezhda': 'clothing',
  'futbolka': 'clothing',
  'rubashka': 'clothing',
  'dzhinsy': 'clothing',
  'kurka': 'clothing',
  'palto': 'clothing',
  'platye': 'clothing',
  'yubka': 'clothing',
  'sviter': 'clothing',
  'kofta': 'clothing',
  'kostyum': 'clothing',
  'shapka': 'clothing',
  'perchatki': 'clothing',
  'noski': 'clothing',
  'beloe': 'clothing',
  'obuv': 'clothing',
  'krossovki': 'clothing',
  'botinki': 'clothing',
  'tufli': 'clothing',

  //ДОМ
  'kuhnya': 'home',
  'dom': 'home',
  'mebel': 'home',
  'divan': 'home',
  'krovat': 'home',
  'stol': 'home',
  'stul': 'home',
  'shkaf': 'home',
  'posuda': 'home',
  'tarelka': 'home',
  'kruzhka': 'home',
  'kofevark': 'home',
  'kofemasina': 'home',
  'cofevark': 'home',
  'polotence': 'home',
  'postelnoe_belye': 'home',
  'dekor': 'home',
  'tekstil': 'home',
  'svetilnik': 'home',
  'lampa': 'home',
  'bytovaya_tekhnika': 'home',
  'vannaya': 'home',

  //СПОРТ
  'sport': 'sports',
  'trenazher': 'sports',
  'ganteli': 'sports',
  'kovrik_dlya_yogi': 'sports',
  'myach': 'sports',
  'raketka': 'sports',
  'velosiped': 'sports',
  'samokat': 'sports',
  'sportivnaya_sumka': 'sports',
  'forma': 'sports',
  'snaryazhenie': 'sports',
  'lyzhi': 'sports',
  'konki': 'sports',
  'turizm': 'sports',
  'palatka': 'sports',
  'ryukzak': 'sports',

  //АКСЕССУАРЫ
  'zaryadki': 'accessories',
  'zaryadka': 'accessories',
  'aksessuary': 'accessories',
  'sumka': 'accessories',
  'chehol': 'accessories',
  'kabel': 'accessories',
  'poverbank': 'accessories',
  'powerbank': 'accessories',
  'usb_flashka': 'accessories',
  'chasy': 'accessories',
  'ochki': 'accessories',
  'solnechnye_ochki': 'accessories',
  'koshelok': 'accessories',
  'remen': 'accessories',
  'remeshok': 'accessories',
  'portfel': 'accessories',
  'zont': 'accessories',
  'shlyapa': 'accessories',
  'brosh': 'accessories',
  'sergi': 'accessories',
  'koltso': 'accessories',
  'tsepochka': 'accessories'
};

// 2. Регулярные выражения для сложных случаев
export const REGEX_MAP = [
  //ЭЛЕКТРОНИКА
  { pattern: /.*smartfon.*/i, category: 'electronics' },
  { pattern: /.*telefon.*/i, category: 'electronics' },
  { pattern: /.*mobile.*/i, category: 'electronics' },
  { pattern: /.*noutbuk.*/i, category: 'electronics' },
  { pattern: /.*laptop.*/i, category: 'electronics' },
  { pattern: /.*kompyuter.*/i, category: 'electronics' },
  { pattern: /.*planhet.*/i, category: 'electronics' },
  { pattern: /.*tablet.*/i, category: 'electronics' },
  { pattern: /.*naushniki.*/i, category: 'electronics' },
  { pattern: /.*kolonki.*/i, category: 'electronics' },
  { pattern: /.*monitor.*/i, category: 'electronics' },
  { pattern: /.*klaviatura.*/i, category: 'electronics' },
  { pattern: /.*myshka.*/i, category: 'electronics' },
  { pattern: /.*televizor.*/i, category: 'electronics' },
  { pattern: /.*tv.*/i, category: 'electronics' },
  { pattern: /.*smart.chas.*/i, category: 'electronics' },
  { pattern: /.*fitnes.braslet.*/i, category: 'electronics' },
  { pattern: /.*konsol.*/i, category: 'electronics' },
  { pattern: /.*fotoapparat.*/i, category: 'electronics' },
  { pattern: /.*kamera.*/i, category: 'electronics' },
  { pattern: /.*router.*/i, category: 'electronics' },
  { pattern: /.*wifi.*/i, category: 'electronics' },

  //ОДЕЖДА
  { pattern: /.*odezhda.*/i, category: 'clothing' },
  { pattern: /.*futbolka.*/i, category: 'clothing' },
  { pattern: /.*rubashka.*/i, category: 'clothing' },
  { pattern: /.*dzhinsy.*/i, category: 'clothing' },
  { pattern: /.*shtany.*/i, category: 'clothing' },
  { pattern: /.*kurka.*/i, category: 'clothing' },
  { pattern: /.*palto.*/i, category: 'clothing' },
  { pattern: /.*platye.*/i, category: 'clothing' },
  { pattern: /.*yubka.*/i, category: 'clothing' },
  { pattern: /.*sviter.*/i, category: 'clothing' },
  { pattern: /.*kofta.*/i, category: 'clothing' },
  { pattern: /.*kostyum.*/i, category: 'clothing' },
  { pattern: /.*pidzhak.*/i, category: 'clothing' },
  { pattern: /.*shapka.*/i, category: 'clothing' },
  { pattern: /.*perchatki.*/i, category: 'clothing' },
  { pattern: /.*noski.*/i, category: 'clothing' },
  { pattern: /.*obuv.*/i, category: 'clothing' },
  { pattern: /.*krossovki.*/i, category: 'clothing' },
  { pattern: /.*botinki.*/i, category: 'clothing' },
  { pattern: /.*tufli.*/i, category: 'clothing' },
  { pattern: /.*sandali.*/i, category: 'clothing' },

  // ДОМ
  { pattern: /.*kuhnya.*/i, category: 'home' },
  { pattern: /.*dom.*/i, category: 'home' },
  { pattern: /.*mebel.*/i, category: 'home' },
  { pattern: /.*divan.*/i, category: 'home' },
  { pattern: /.*sofa.*/i, category: 'home' },
  { pattern: /.*krovat.*/i, category: 'home' },
  { pattern: /.*matras.*/i, category: 'home' },
  { pattern: /.*stol.*/i, category: 'home' },
  { pattern: /.*stul.*/i, category: 'home' },
  { pattern: /.*shkaf.*/i, category: 'home' },
  { pattern: /.*polka.*/i, category: 'home' },
  { pattern: /.*posuda.*/i, category: 'home' },
  { pattern: /.*tarelka.*/i, category: 'home' },
  { pattern: /.*kruzhka.*/i, category: 'home' },
  { pattern: /.*chashka.*/i, category: 'home' },
  { pattern: /.*kasterulya.*/i, category: 'home' },
  { pattern: /.*skovoroda.*/i, category: 'home' },
  { pattern: /.*polotence.*/i, category: 'home' },
  { pattern: /.*postelnoe.*/i, category: 'home' },
  { pattern: /.*podushka.*/i, category: 'home' },
  { pattern: /.*odeyalo.*/i, category: 'home' },
  { pattern: /.*dekor.*/i, category: 'home' },
  { pattern: /.*vaza.*/i, category: 'home' },
  { pattern: /.*svetilnik.*/i, category: 'home' },
  { pattern: /.*lampa.*/i, category: 'home' },
  { pattern: /.*lyustra.*/i, category: 'home' },
  { pattern: /.*pylesos.*/i, category: 'home' },
  { pattern: /.*stiralka.*/i, category: 'home' },
  { pattern: /.*holodilnik.*/i, category: 'home' },
  { pattern: /.*mikrovolnovka.*/i, category: 'home' },
  { pattern: /.*vannaya.*/i, category: 'home' },
  { pattern: /.*kover.*/i, category: 'home' },
  { pattern: /.*shtory.*/i, category: 'home' },

  // СПОРТ
  { pattern: /.*sport.*/i, category: 'sports' },
  { pattern: /.*trenazher.*/i, category: 'sports' },
  { pattern: /.*ganteli.*/i, category: 'sports' },
  { pattern: /.*shtanga.*/i, category: 'sports' },
  { pattern: /.*yoga.*/i, category: 'sports' },
  { pattern: /.*kovrik.*/i, category: 'sports' },
  { pattern: /.*myach.*/i, category: 'sports' },
  { pattern: /.*basketbol.*/i, category: 'sports' },
  { pattern: /.*futbol.*/i, category: 'sports' },
  { pattern: /.*tennis.*/i, category: 'sports' },
  { pattern: /.*raketka.*/i, category: 'sports' },
  { pattern: /.*velosiped.*/i, category: 'sports' },
  { pattern: /.*samokat.*/i, category: 'sports' },
  { pattern: /.*lyzhi.*/i, category: 'sports' },
  { pattern: /.*snoubord.*/i, category: 'sports' },
  { pattern: /.*konki.*/i, category: 'sports' },
  { pattern: /.*rolki.*/i, category: 'sports' },
  { pattern: /.*kaska.*/i, category: 'sports' },
  { pattern: /.*zashhita.*/i, category: 'sports' },
  { pattern: /.*forma.*/i, category: 'sports' },
  { pattern: /.*rybalka.*/i, category: 'sports' },
  { pattern: /.*udocka.*/i, category: 'sports' },
  { pattern: /.*turizm.*/i, category: 'sports' },
  { pattern: /.*palatka.*/i, category: 'sports' },
  { pattern: /.*fitnes.*/i, category: 'sports' },
  { pattern: /.*trenirovka.*/i, category: 'sports' },
  { pattern: /.*protein.*/i, category: 'sports' },
  { pattern: /.*beg.*/i, category: 'sports' },

  // АКСЕССУАРЫ
  { pattern: /.*aksessuar.*/i, category: 'accessories' },
  { pattern: /.*zaryadk.*/i, category: 'accessories' },
  { pattern: /.*kabel.*/i, category: 'accessories' },
  { pattern: /.*provod.*/i, category: 'accessories' },
  { pattern: /.*adapter.*/i, category: 'accessories' },
  { pattern: /.*perehodnik.*/i, category: 'accessories' },
  { pattern: /.*chehol.*/i, category: 'accessories' },
  { pattern: /.*steklo.*/i, category: 'accessories' }, // защитное стекло
  { pattern: /.*sumka.*/i, category: 'accessories' },
  { pattern: /.*ryukzak.*/i, category: 'accessories' },
  { pattern: /.*koshelok.*/i, category: 'accessories' },
  { pattern: /.*portfel.*/i, category: 'accessories' },
  { pattern: /.*remen.*/i, category: 'accessories' },
  { pattern: /.*galstuk.*/i, category: 'accessories' },
  { pattern: /.*sharf.*/i, category: 'accessories' },
  { pattern: /.*kepka.*/i, category: 'accessories' },
  { pattern: /.*panama.*/i, category: 'accessories' },
  { pattern: /.*ochki.*/i, category: 'accessories' },
  { pattern: /.*zont.*/i, category: 'accessories' },
  { pattern: /.*brosh.*/i, category: 'accessories' },
  { pattern: /.*sergi.*/i, category: 'accessories' },
  { pattern: /.*koltso.*/i, category: 'accessories' },
  { pattern: /.*tsepochka.*/i, category: 'accessories' },
  { pattern: /.*braslet.*/i, category: 'accessories' },
  { pattern: /.*powerbank.*/i, category: 'accessories' },
  { pattern: /.*flashka.*/i, category: 'accessories' },
  { pattern: /.*kart.*/i, category: 'accessories' }, // карта памяти
  { pattern: /.*derzhatel.*/i, category: 'accessories' }
];

// 3. Сегменты, которые нужно игнорировать (мусор)
export const IGNORE_SEGMENTS = ['catalog', 'product', 'item', 'shop', 'all', 'new', 'sale', 'promо', 'p', 'g'];
